version: '3'

services:
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tutorial-dev
    volumes:
      - './node_modules'
      - '.:/usr/app'
    ports:
      - '3000:3000'
